### ISSUE TITLE
error: asm operand type size(8) does not match type/size implied by constraint 'r'

### ISSUE THREAD

**Issue by ashnarayan13** [ProjectArtemis/tegra_stereo#1]
I am unable to trace the issue for this error. I am compiling the code on ros kinetic and ubuntu16.04 on a jetson tx1. 
Any help on this would be very useful!

**Comment by ashnarayan13** [comment]
@mhkabir I am new to working on the GPU + ROS, any idea what I should be changing?

**Comment by ashnarayan13** [comment]
I changed the following and the code compiled successfully on the tx1. I hope it helps others. 
`__device__ __forceinline__ uint32_t ld_gbl_ca(const __restrict__ uint32_t *addr) {
	uint32_t return_value;
	asm("ld.global.ca.u32 %0, [%1];" : "=r"(return_value) : "l"(addr)); //changed from r to l
	return return_value;
}

__device__ __forceinline__ uint32_t ld_gbl_cs(const __restrict__ uint32_t *addr) {
	uint32_t return_value;
	asm("ld.global.cs.u32 %0, [%1];" : "=r"(return_value) : "l"(addr)); //changed from r to l
	return return_value;
}

__device__ __forceinline__ void st_gbl_wt(const __restrict__ uint32_t *addr, const uint32_t value) {
	asm("st.global.wt.u32 [%0], %1;" :: "l"(addr), "r"(value));//changed from r to l
}

__device__ __forceinline__ void st_gbl_cs(const __restrict__ uint32_t *addr, const uint32_t value) {
	asm("st.global.cs.u32 [%0], %1;" :: "l"(addr), "r"(value));//changed from r to l
}
`

**Comment by mhkabir** [comment]
@ashnarayan13 Thanks!
